"""empty message

Revision ID: d88abf6cfd90
Revises: abc7e10d8631
Create Date: 2023-07-18 16:21:02.442015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88abf6cfd90'
down_revision = 'abc7e10d8631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('climate')
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
